### ISSUE TITLE
Complex properties of entity (Owned entities) cannot be used with EFcore mapper

### ISSUE THREAD

**Issue by MichaelM223** [leonardoporro/Detached-Mapper#101]
When using `Owned` entity type as a property in an entity that is being saved to the database using `MapAsync` an exception throws in `RootEntityTypeMapper` on line 46:

`System.InvalidOperationException: 'The property 'CompanyDetails.Id' is part of a key and so cannot be modified or marked as modified. To change the principal of an existing entity with an identifying foreign key, first delete the dependent and invoke 'SaveChanges', and then associate the dependent with the new principal.'`

Owned types in a collection are working correctly, this issue is only for complex property types only.

````csharp
public class CompanyDetails
{
    public string Name {get; set;}
    public string Address {get; set;}
}

public class MaintenanceForm
{
    [Key]
    public Guid Id {get; set;}
    public string Description {get; set;}
    public CompanyDetails Company {get; set;}
}
````

In dbcontext (need shadow id because I want to use multiple `CompanyDetails` properties in `MaintenanceForm`:
````csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<MaintenanceForm>(entity =>
    {
        entity.Property(e => e.Id)
            .HasDefaultValueSql("newsequentialid()");
        entity.OwnsOne(e => e.Company , nb => { 
            nb.ToJson();
            nb.Property<Guid>("Id").ValueGeneratedOnAdd();
            nb.HasKey("Id");
        });
}
````

Create entity with a property of a complex type and save the entity with `MapAsync` on a EFcore context.

**Expected behavior**
Entity should be saved including complex type data (in my case mapped to a json column, configured in efcore dbcontext)

EFcore 7.0
.NET 7.0
Latest detached-mapper

Might be related to issue #60 ?

**Comment by MichaelM223** [comment]
Might have forgotten the `[Composite]` attribute (thought that was only for collections), will check it out soon

**Comment by leonardoporro** [comment]
Yes, it is for both, references and collections. Please let me know if it
works.

**Comment by MichaelM223** [comment]
This was my fault, forgot the composite tag for OwnedTypes
