### ISSUE TITLE
[NotMapped] Attribute causes a cast error

### ISSUE THREAD

**Issue by Letsion** [leonardoporro/Detached-Mapper#105]
[NotMapped] Attribute causes a cast error with the MapIgnoreAnotationHandler.

Fix:
Write your Own Anotation Handler for NotMappedAttribute:
```
using System.ComponentModel.DataAnnotations.Schema;
using Detached.Mappers;
using Detached.Mappers.Annotations;
using Detached.Mappers.Types.Class;

namespace BOB.Backend.Common.AttributeHandlers
{
    public class NotMappedAnnotationHandler : AnnotationHandler<NotMappedAttribute>
    {
        public override void Apply(NotMappedAttribute annotation, MapperOptions mapperOptions, ClassType typeOptions, ClassTypeMember memberOptions)
        {
            memberOptions.Ignore(true);
        }
    }
}
```

**Comment by leonardoporro** [comment]
Hi Nico,
Yup, there was a missing handler over there.. removed in 7.1.2.
I thought we agreed not to stop mapping for [NotMapped] but only for [MapIgnore].

A better workardound would be `options.AnnotationHandlers.Remove(typeof(NotMappedAttribute));`

Anyway, you already know how to create your own handlers, so, excellent..

**Comment by Letsion** [comment]
The problem was, it should map with NotMapped the properties anyway, which is not in the database.
If I now remove NotMapped from the AnnotationHandlers Dictornary then he wants to load the Ef Core but they are not in the database = Error.
Suggested solution:
For the NotMapped attribute, map the values from the DTo to the entity but don't try to load them from the database.
