### ISSUE TITLE
Is there a way to use a profile to explicitly map properties with differing names?

### ISSUE THREAD

**Issue by McPhale** [leonardoporro/Detached-Mapper#113]
Eg, in automapper you can do something like this:

```csharp
CreateMap<Comment, CommentDTO>().ForMember(cdto => cdto.Comment, config => config.MapFrom(c => c.CommentText)).ReverseMap();
```
when property names don't exactly match between entity and dto. I see you've done some work to support mapping profiles but don't see a way to get this behavior that I'm after.

This library looks pretty handy, thank you for working on it :)

**Comment by leonardoporro** [comment]
Hi @McPhale, thank you!
[This](https://github.com/leonardoporro/Detached-Mapper/blob/cf06d5829a082ac9acfea0f0f6666a68cc7e4a87/test/Detached.Mappers.EntityFramework.Tests/Features/ConfigureProfiles.cs#L85) is the closest thing we have.

`mapperOptions.Type<T1>().FromType<T2>().` and then FromMember allows to redirect to another member, or FromValue lets you specify a custom expression.
Source for that is [here](https://github.com/leonardoporro/Detached-Mapper/blob/cf06d5829a082ac9acfea0f0f6666a68cc7e4a87/src/Detached.Mappers/TypePairs/Builder/TypePairMemberBuilder.cs#L16C1-L17C1)

**Comment by leonardoporro** [comment]
The idea of the profiles is that you can add multiple configurations for the same type pair, depending on a key.
For example, for the "create" profile an Id is not mapped but for "edit" profile, it is.
(I hope nobody really needs to use profiles anyway... )

I didn't want to create an AutoMapper replacement, so this library won't have as much options as it. But rename, custom and ignore are available.

When I started the library, I wanted to create an extension for AutoMapper, but after version 9 it has explicit configuration which makes it a real headache to use it.

**Comment by McPhale** [comment]
Thank you! I'm pulled off on other stuff now but I hope to come back to playing around with this later, thank again
