### ISSUE TITLE
Mapper doesn't work when using concurrency token as Timestamp/Rowversion

### ISSUE THREAD

**Issue by ricabrica** [leonardoporro/Detached-Mapper#26]
Usually the token is mapped to a byte[] and the error looks like the folowing. If there is a workaround, please share it.

Message: 
    System.InvalidOperationException : Can't construct byte[]. It does not have a parameterless constructor or a concrete type specified.
  Stack Trace: 
    ClassTypeOptions.Construct(Expression context)
    ListMapperFactory.Create(TypeMap typeMap)
    MapperFactory.CreateMapper(TypeMap typeMap)
    MapperFactory.CreateMemberMappers(TypeMap typeMap, Func`2 filter)
    EntityListMapperFactory.Create(TypeMap typeMap)
    MapperFactory.CreateMapper(TypeMap typeMap)
    MapperFactory.CreateMemberMappers(TypeMap typeMap, Func`2 filter)
    EntityListMapperFactory.Create(TypeMap typeMap)
    MapperFactory.CreateMapper(TypeMap typeMap)
    MapperFactory.CreateMemberMappers(TypeMap typeMap, Func`2 filter)
    EntityRootMapperFactory.Create(TypeMap typeMap)
    Mapper.<Map>b__6_0[TSource,TTarget](ICacheEntry entry)
    CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
    Mapper.Map[TSource,TTarget](TSource source, TTarget target, IMapperContext context)
    lambda_method(Closure , Object , Object , IMapperContext )
    Mapper.Map(Object source, Type sourceType, Object target, Type targetType, IMapperContext context)
    DbContextExtensions.Map[TEntity](DbContext dbContext, Object entityOrDTO, MapperParameters parameters)

**Comment by leonardoporro** [comment]
Hi @ricabrica, thanks for writing

That error message means that byte[] is not being taken as a primitive, so that, the library handles it as an object.
On the other hand, primitives are copied 'as-is'.
It can be fixed by adding the type to primitives:
`
 .UseDetached(options => options.Primitives.Add(typeof(byte[])))
`
Do you think I should add it by default?

**Comment by ricabrica** [comment]
Hi @leonardoporro,

byte[] is specific to SQL Server. if your library is SQL agnostic, than let the byte[] out. UseDetached is a good  and a viable option. Thanks for your info.

**Comment by leonardoporro** [comment]
Ok, I'll add more tests about arrays later. 
Please let me know if it works...

**Comment by leonardoporro** [comment]
Collections of primitives are now processed as primitives.
