### ISSUE TITLE
Instructions unclear, DetachedDbContext does not exist anymore

### ISSUE THREAD

**Issue by Jogai** [leonardoporro/Detached-Mapper#31]
The instructions mention DetachedDbContext but it was removed lately. Do the other instructions still apply?

**Comment by leonardoporro** [comment]
Hi @Jogai, thanks for pointing that out.
Yes, the other options, including the UseDetached() extension works, I just forgot to update that part about DetachedDbContext.
Sorry, I'm doing this library for a personal use and wanted to share it, but it's difficult to maintain it without help.

**Comment by Jogai** [comment]
Thanks.

You're doing awesome! At least you have something published, and reply quick :)

**Comment by leonardoporro** [comment]
Thanks @Jogai, if you use it, please let me know how it goes here in github, or to mail@leonardoporro.com.ar.
Thanks!
