### ISSUE TITLE
Preserving unloaded related data

### ISSUE THREAD

**Issue by Jogai** [leonardoporro/Detached-Mapper#37]
**Describe the bug**
Sorry, here I am again.
Repro here: https://dotnetfiddle.net/wDbM8i
Parent is being saved with some stuff changed but with 
The parent has a one-to-many to details but when saving the parent without details loaded I get an error:

```
The association between entity types 'Parent' and 'Detail' has been severed, but the relationship is either marked as required or is implicitly required because the foreign key is not nullable. If the dependent/child entity should be deleted when a required relationship is severed, configure the relationship to use cascade deletes. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Program.Main()
Command terminated by signal 6
```

**Expected behavior**
Expectation is to save everything, and leave all the associated details as is.

**Additional context**
I think my fiddle is using 5.0.21 but I ran into this with 5.0.22. It might be that Detached-PatchTypes is the solution to this, but I'm using newtonsoft json for serializing requests so I couldn't get that to work in my project.

**Comment by leonardoporro** [comment]
Hi again,
Yes, it is the "undefined" issue that comes with C#, null is a value, and will be saved as null, overriding any previous existing value.
And yes again, PatchTypes is one possible solution... I was sure newtonsoft was already deprecated, but will try to make it work and let you know.
Another posibility would be to use more DTOs, and just omit the values you don't want to map. GraphQL papers recommend to have 1 class per command, and usually calls it [Command]Input... for example SaveUserInput. This can be applied to Rest too.
Go to your fiddle and delete "Parent" after the "new" keyword, it will become an anonymous class and the mapping will work.

context.Map<Parent>(new Parent{Id = 1...
context.Map<Parent>(new {Id = 1...

Thanks for your feedback, as you help me to improve the library.
It's only me here, and I have few time, no help and negative money :) so if you like the library I'd be grateful if you mention it to your colleagues, maybe we can involve more people.

I'll let you know what happens with newtonsoft.

**Comment by Jogai** [comment]
> I was sure newtonsoft was already deprecated
MS is trying to make it so... But google a bit, everyone is still using it seems to me.

But yeah, you're right, I should make proper viewmodels.

> Thanks for your feedback, as you help me to improve the library.
Thank you for responding that quick! For a one man maintainer you're doing terrific!

> maybe we can involve more people
I'm trying to wrap my head around it, but so far its a bit much

> I'll let you know what happens with newtonsoft.
Thanks a ton!

**Comment by leonardoporro** [comment]
Not sure if you saw it in the other project, but already implemented newtonsoft converter for patch types
