### ISSUE TITLE
.net6 results in error

### ISSUE THREAD

**Issue by MaRRiK74** [leonardoporro/Detached-Mapper#40]
Hi, Because .net6 is released now. I wanted to test detached-mapper and this results in the following error (used with entity framework)

System.TypeLoadException: 'Method 'GetServiceProviderHashCode' in type 'Detached.Mappers.EntityFramework.Extensions.DetachedDbContextOptionsExtensionInfo' from assembly 'Detached.Mappers.EntityFramework, Version=5.0.23.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

**Comment by leonardoporro** [comment]
Will update to net 6 this night

**Comment by leonardoporro** [comment]
6.0 is out
it seems that ef 6 doesn't support net standard, so that, I had to move Detached.Mappers.EntityFramework to net 6, which is ok, I think.
please let me know if it works for you

**Comment by MaRRiK74** [comment]
Sorry, still the same error

System.TypeLoadException: 'Method 'GetServiceProviderHashCode' in type 'Detached.Mappers.EntityFramework.Extensions.DetachedDbContextOptionsExtensionInfo' from assembly 'Detached.Mappers.EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

**Comment by leonardoporro** [comment]
I think the problem was that the sample still containing ef 5 references, and that made it work.
(should stop doing changes late at night)
please try 6.0.1

**Comment by MaRRiK74** [comment]
all tests passed. Seems ok now! Thank you for the quick fix

**Comment by MaRRiK74** [comment]
@leonardoporro This issue is still present in the test project
