### ISSUE TITLE
Add dependabot? Dependencies will get updated automatically

### ISSUE THREAD

**Issue by MaRRiK74** [leonardoporro/Detached-Mapper#42]
With this all related dependencies will be updated.

https://github.com/dependabot

**Comment by leonardoporro** [comment]
Hey, thanks for the suggestion, I'll take a look.

I'm glad you are interested in the library, I created it after years and years of writting the same code. It's cool to accelerate CRUDs (I don't recommend it for high traffic endpoints, as it loads a copy from the DB for the comparison).

But actually I don't even work with EF and am really short on time for maintainance. And I also didn't manage to involve more people on it.

If you want to share ideas, or tell me about your project, feel free to reach me out, my linkedin and email are in the main readme.
