### ISSUE TITLE
Two levels of composition doesn't work

### ISSUE THREAD

**Issue by traiannemes** [leonardoporro/Detached-Mapper#44]
**Describe the bug**
Two levels of composition doesn't work with EF Core

**To Reproduce**
Invoice -> Invoice Line Item -> Invoice Item details

```
class Invoice
{
    [Composition] 
    List<InvoiceLineItem> InvoiceLineItems { get; set; }
}

class InvoiceLineItem
{
    [Composition]

    List<InvoiceItemDetails> InvoiceItemDetails { get; set; }
}

class InvoiceItemDetails
{
   
}
```
**Expected behavior**
MapAsync to track down to second level, it only tracks first with EF Core and all InvoiceItemDetails are tracked as Added.

**Comment by tomesendam** [comment]
I've also gotten this problem, Although for me it's 3 levels deep. Is there an ETA on this? or general priority

**Comment by leonardoporro** [comment]
Hey, sorry for the delay...

 @tomesendam @traiannemes  Could you please help me to reproduce the bug based on this test? 
[Map Two Levels Integration Test](https://github.com/leonardoporro/Detached-Mapper/blob/bugfix/map-two-levels/test/Detached.Mappers.EntityFramework.Tests/MapTwoLevels.cs)
Please send a pr, or copy/paste or whatever is easier for you...
Thank you!

**Comment by tomesendam** [comment]
If I don't forget I'll do it in the afternoon

**Comment by leonardoporro** [comment]
Hey, were you able to check the test? 
Would be possible for you to post an exact copy of the model that is failing?

**Comment by traiannemes** [comment]
Your unit test is tracking the entities and that's why it's working.
At line 40 in the unit test please add "db.ChangeTracker.Clear();" (basically after you save the first time)
And then the test will fail.

It will work if we eagerly go ahead before await db.MapAsync<>() call and load all the entities from the DB that are in the graph.

If we don't do that than the composition works a single level down.

**Comment by traiannemes** [comment]
Hi Leonardo, by any chance any progress on this? I love the work you've done so far. Thanks!

**Comment by leonardoporro** [comment]
Thank you, and sorry for the loooooooooooong delay (personal issues and don't have any help).
I published 6.0.2 and 5.0.14, would you like to test?

**Comment by traiannemes** [comment]
It works like a charm! Thank you Leonardo, really great job! I love it!

**Comment by traiannemes** [comment]
Leonardo, just as a suggestion on tracking delete entities. When a parent-child relation is set to cascade on delete it would be more efficient to just mark the parent with delete status, SQL will take care of the child table. Right now all child entities are marked as deleted and deleted from database before parent table record is, too
