### ISSUE TITLE
Postgresql integration with NpgsqlTsVector field type

### ISSUE THREAD

**Issue by PatAmb63** [leonardoporro/Detached-Mapper#46]
**Describe the bug**
I am using PostgresSQL 14 database with the field for Full Text Search.
You can find detail here : https://www.npgsql.org/efcore/mapping/full-text-search.html?tabs=pg12%2Cv5
When i use context.MapAsync() function i've got an error and the application fail.

**To Reproduce**
1. create an entity with NpgsqlTsVector field
2. create migration and database
3. create a new reference of the entity
4. use context.MapAsync() function
5. You can see the error message is : System.ArgumentException: Incorrect number of arguments supplied for call to method 'WordEntryPos get_Item(Int32)' (Parameter 'property')

**Expected behavior**
Could you correct the bug or tell me a walk around to be able to use this field with Map function.

**Comment by leonardoporro** [comment]
Please try by adding your type as a primitive, so the mapper doesn't try to
map it property by property.
 .UseDetached(cfg =>
{
     cfg.Primitives.Add(typeof(NpgsqlTsVector));
})

**Comment by PatAmb63** [comment]
Thank you !
That work fine.
BR
Patrice

**Comment by PatAmb63** [comment]
I have an other question.
How to ask Detached to ignore the update for this kind of field ?
BR
Patrice

**Comment by leonardoporro** [comment]
Sorry for the delay.
Please try something like this:

` .UseDetached(cfg =>
{
    cfg.Configure<User>().Member(u => u.Name).MemberOptions.Ignored = true;
})`

I used to have a [DetachedIgnore] attribute... I can't rembemer when I removed... but need to add it again.

**Comment by leonardoporro** [comment]
I remember now! changed to System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute.
Please try [NotMapped] on the member to ignore.

Really need to improve the documentation... help is very welcome :)
