### ISSUE TITLE
ArgumentException: Static property requires null instance, non-static property requires non-null instance. (Parameter 'expression')

### ISSUE THREAD

**Issue by PeterDraex** [leonardoporro/Detached-Mapper#48]
Hello!
I'm trying to use Detached-Mapper for the first time. I've installed the NuGet package and registered the dependencies. I was hit by the following error:
> ArgumentException: Static property requires null instance, non-static property requires non-null instance. (Parameter 'expression')
System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)

With stack trace:
> System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
Detached.Mappers.TypeOptions.Types.Class.ClassOptionsFactory.Create(MapperOptions options, Type type)
Detached.Mappers.MapperOptions+<>c__DisplayClass27_0.<GetTypeOptions>b__0(Type keyType)
System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd(TKey key, Func<TKey, TValue> valueFactory)
Detached.Mappers.MapperOptions.GetTypeOptions(Type type)
Detached.Mappers.TypeMaps.TypeMapFactory.IsBackReference(MapperOptions options, TypeMap typeMap, IMemberOptions memberOptions, out BackReferenceMap backReferenceMap)
Detached.Mappers.TypeMaps.TypeMapFactory.Create(Mapper mapper, MapperOptions options, TypeMap parentMap, Type sourceType, Type targetType, bool isComposition)
Detached.Mappers.Mapper.GetTypeMap(Type sourceType, Type targetType)
Detached.Mappers.Mapper.<Map>b__6_0<TSource, TTarget>(ICacheEntry entry)
Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate<TItem>(IMemoryCache cache, object key, Func<ICacheEntry, TItem> factory)
Detached.Mappers.Mapper.Map<TSource, TTarget>(TSource source, TTarget target, IMapperContext context)
lambda_method206(Closure , object , object , IMapperContext )
Detached.Mappers.Mapper.Map(object source, Type sourceType, object target, Type targetType, IMapperContext context)
Detached.Mappers.EntityFramework.DbContextExtensions.Map<TEntity>(DbContext dbContext, object entityOrDTO, MapperParameters parameters)
FirmBasket.Server.Controllers.SyncController.Slovakia() in SyncController.cs
                           context.Map<Organization>(changedOrganization);

My code:
```csharp
var response = await client.GetAsync("https://datahub.ekosystem.slovensko.digital/api/data/rpo/organizations/sync");
response.EnsureSuccessStatusCode();

var changedOrganizations = await response.Content.ReadFromJsonAsync<Organization[]>();
if(changedOrganizations != null)
{
    foreach (var changedOrganization in changedOrganizations)
    {
         context.Map<Organization>(changedOrganization);
    }
}
```
The Organization is a database entity - definition on [pastebin](https://pastebin.com/c9qC7yRi).
![image](https://user-images.githubusercontent.com/18402223/168422104-12a5684a-97ce-49b2-bbf0-a5252ec04cee.png)

Any tips on what can be causing the exception?

**Comment by leonardoporro** [comment]
Hi @PeterDraex 

The issue is because the type DateOnly is not registered as a primitive, and the library is trying to map it memember by member like an entity.
Please add this until I release the next version including DateOnly as a primitive.
```csharp
                    .UseDetached(cfg =>
                    {
                        cfg.Primitives.Add(typeof(DateOnly));
                    })
```
On the other hand, ICollection is not supported yet, the library works with IList because it access items by index internally. So HashSet is not being supported.
Please give it a try with the primitive and temporary change ICollection to IList, if you plan to use the library I'll give priority to a solution for this.
Thanks for the feedback
Cheers

**Comment by PeterDraex** [comment]
I've registered `DateOnly` and `NpgsqlTypes.NpgsqlTsVector` as primitives and replaced `ICollection` with `List` and now it goes through! Thanks for your help!

I'm leaving the issue open in case you want to use it to track support for `IEnumerable` types / better error message. Otherwise, feel free to close it.

**Comment by leonardoporro** [comment]
latest version supports abstracts, interfaces and inheritance with discriminators, including ICollection
need to update the documentation, btw

**Comment by Jogai** [comment]
> ```cs
> .UseDetached(cfg =>
>                     {
>                         cfg.Primitives.Add(typeof(DateOnly));
>                     })
> ```

Just fyi, I still need to do this.
