### ISSUE TITLE
Allow mapping of composition enumerables with a getter only

### ISSUE THREAD

**Issue by jorgeparavicini** [leonardoporro/Detached-Mapper#55]
I usually define collections in my entities with a getter only like this:
```C#
public class GroupReservation
{
    [Key]
    public int Id { get; set; }
    public string? Reference { get; set; }
    [Composition]
    public List<Reservation> Reservations { get; } = new List<Reservation>();
}
```

However, when Mapping a DTO to such an entity, the collections will remain empty. To fix this one, the collection on the entity requires a setter:

```C#
public class GroupReservation
{
    [Key]
    public int Id { get; set; }
    public string? Reference { get; set; }
    [Composition]
    public List<Reservation> Reservations { get; set; }
}
```

I would therefore like to ask if it would be possible to allow collections with a getter only to be mapped.

**Comment by leonardoporro** [comment]
Hi @jorgeparavicini, 
Right now, all properties are set, independently of the collection being recreated or not.
Let me check if I can patch it to support this scenario..

**Comment by leonardoporro** [comment]
Added from v7.2.0.
Please reopen if you find issues.
