### ISSUE TITLE
Configure associations for each map operation

### ISSUE THREAD

**Issue by cryo75** [leonardoporro/Detached-Mapper#60]
I have quite a large project which I just migrated to NET7. Unfortunately the DAL project is sill using EF6 (6.4.4) because it uses GraphDiff for updates (and inserts). A simple example might be:

```csharp 
    var updated = ((DbContext)dataContext).UpdateGraph<Customer>
        (entity,
            map => map.AssociatedEntity(x => x.CustomerType)
                        .AssociatedEntity(x => x.Title)
                        .AssociatedEntity(x => x.Gender)
                        .OwnedEntity(x => x.Address, with => with
                            .AssociatedEntity(t => t.Title)
                            .AssociatedEntity(p => p.PostCode))
                        .OwnedEntity(x => x.BillingAddress, with => with
                            .AssociatedEntity(t => t.Title)
                            .AssociatedEntity(p => p.PostCode))
                        .OwnedEntity(x => x.ShippingAddress, with => with
                            .AssociatedEntity(t => t.Title)
                            .AssociatedEntity(p => p.PostCode))
                        .OwnedCollection(x => x.BankCodes, with => with
                            .AssociatedEntity(t => t.AccountHolder))
                        .OwnedCollection(x => x.Creditcards, with => with
                            .AssociatedEntity(t => t.Title)
                            .AssociatedEntity(b => b.BankCode)
                            .AssociatedEntity(c => c.Creditcard))
```

This is still working fine but it is time to upgrade to EFCore. The entity that is passed to the update method has been already mapped from DTO to a model at an earlier stage, so mapping from DTO to models is not required.

One problem that I see with using the `Aggregation` and `Composition` attributes at the property level is that some object graphs get way too complex. For example in the above, PostCode is associated with Address. However PostCode has further links to additional classes such as State, County and Country. When saving the customer these additional classes do not need to be loaded and updated. So that it why they are not included above. 

Is it possible to add extensions to Detached to mimic the above GraphDiff methods?

**Comment by leonardoporro** [comment]
@cryo75 Hi, thanks for writing,
Yes, this is the next thing I'm going to work on. Hope to have it ready for January.
Help on testing and so is very appreciated!

**Comment by leonardoporro** [comment]
started working on profiles!
a big difference between GraphDiff and Detached.Mappers is that the last one works with static compiled expression trees
so there is no way to dinamically evaluate if a property is going to be included or not and what's the type in runtime, without loosing a lot of performance and other features
profiles allows to create a different mapper for each scenario and decide what is going to be included or not, or whats an association or composition.
please take a look at [this](https://github.com/leonardoporro/Detached-Mapper/issues/54)

you may do something like this to mimic the sample you sent:
`
 mapping.AddProfile(MappingProfiles.SaveAll, cfg =>
    {
        cfg.Type<Customer>()
             .Member(u => u.CustomerType).Association()
             .Member(u => u.Title).Association();
       
       cfg.Type<Address>()
             .Member(u => u.Title).Association()
             .Member(u => u.PostCode).Association();
    });
`
I need to add more samples and maybe extension methods to make it easier and more similar to what you are asking for...
(also tests and/or extensions are very welcome if you want to push something to the repo)
have a nice weekend!

**Comment by cryo75** [comment]
My example above shows how I save the customer entity. The `PostCode` is used as association in `Address`. Here is how I save the postcode itself:

```csharp
var updated = ((DbContext)dataContext).UpdateGraph<PostCode>
    (entity, map => map.AssociatedEntity(x => x.County)
       .AssociatedEntity(x => x.State)
       AssociatedEntity(x => x.Country)
    );
```

So if I upgrade to Detached I will need to have add a profile in each and every store, so when saving the customer and will have the postcode as association without its own associations. And when I save the postcode it will have its associations as show above. Is this so?

**Comment by leonardoporro** [comment]
Yup, you may have an enum to use as a key (key is Object so you can pass anything to it):
`
enum SaveMode { Create, Update }
`
then configure
`
.UseMapping(mapping => {
        mapping.AddProfile(SaveMode.Update, cfg =>
        {
              cfg.Type<PostCode>()
                   .ExcludeAll()
                   .Member(u => u.Id).Include() // Detached won't work without an Id to compare by.
                   .Member(u => u.Country).Include().Association() // include Country and mark it as association.
                   .Member(u => u.State).Include().Association() // include State and mark it as association.
        });
`
finally map:
`
  dbContext.Map<PostCode>(SaveMode.Update, new { ....)
`


maybe I can make Association to also call Include to simplify...
it was a quick implementation... needs more feedback

**Comment by cryo75** [comment]
What is the `mapping` instance and how do I pass it on to my repository classes? 

In which namespace is the `MappingProfiles` found?

**Comment by leonardoporro** [comment]
.UseMapping is new in 6.4.0, it's the replacement of UseDetached that supports profiles.
Profiles (for now) must be created when the dbcontext is configured.

**Comment by leonardoporro** [comment]
Working on new Wiki to explain everything, but will take some time

**Comment by leonardoporro** [comment]
https://github.com/leonardoporro/Detached-Mapper/blob/8ae250a52d8c30be1e81f9b87c69fd2b4e0f7e85/test/Detached.Mappers.EntityFramework.Tests/ProfilesTests.cs#L40

**Comment by cryo75** [comment]
No problem. Started porting the entities and mappings to EF7 before adding Detached stuff.

**Comment by leonardoporro** [comment]
Sure, I'll add or help you to add missing features that you need

**Comment by cryo75** [comment]
It is also important to remember that the profile will be used for loading the entity and all its associations and compositions so that its added to the change tracker before the mapping/diff is done, and before saving.

**Comment by leonardoporro** [comment]
Can't find any task for me here right now. Please reopen if you need anything.
