### ISSUE TITLE
Readme shows wrong example

### ISSUE THREAD

**Issue by Jogai** [leonardoporro/Detached-Mapper#61]
The example in the readme seems wrong after I upgraded to 6.2.2 (came from 6.0.6)

This:

```C#
services.AddDbContext<MainDbContext>(cfg =>
    {
        ...
        cfg.UseDetached(options => {
            options.Configure<Invoice>().Member(i => i.Rows).Composition();
        });
    });
```

Works only as I change it into this:

```C#
services.AddDbContext<MainDbContext>(cfg =>
    {
        ...
        cfg.UseDetached(options => {
            options.Type<Invoice>().Member(i => i.Rows).IsComposition(true);
        });
    });
```

If I'm reading that correct?

**Comment by leonardoporro** [comment]
Yup, sorry... actively working on the new doc. here in the wiki: https://github.com/leonardoporro/Detached-Mapper/wiki/Getting-Started
also had to downgrade netstandard from 2.1 to 2.0 to make dotnetfiddle work again
in a couple of weeks will simplify the main page and make it point to the wiki

**Comment by Jogai** [comment]
Awesome. The fiddle link on the wiki isnt working for me ;)

**Comment by leonardoporro** [comment]
> 

No, yesterday I had to downgrade netstandard from 2.1 to 2.0 because it wasn't working on dotnetfiddle
Will update soon

**Comment by leonardoporro** [comment]
New wiki published.. Still need work on a lot of articles
