### ISSUE TITLE
Is [Entity] attribute required?

### ISSUE THREAD

**Issue by cryo75** [leonardoporro/Detached-Mapper#63]
I'm migrating my models to EF Core and Detached. Do I still need the `[Entity]` attribute on my model classes or is it handled by EF Core?

**Comment by leonardoporro** [comment]
No, you don't need to add it. 
It is handled by this: https://github.com/leonardoporro/Detached-Mapper/blob/8ae250a52d8c30be1e81f9b87c69fd2b4e0f7e85/src/Detached.Mappers.EntityFramework/Conventions/EFConventions.cs#L21
You may add your own conventions too.

**Comment by cryo75** [comment]
Good. Thanks.
