### ISSUE TITLE
Configure array of primitives as primitive by default  (Error with RowVersion column)

### ISSUE THREAD

**Issue by traiannemes** [leonardoporro/Detached-Mapper#67]
Have an entity like
public class Timesheet 
{
    public int TimesheetId { get; set; }
    
    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    [Timestamp]
    public byte[] RowVersion { get; set; }

}

Update like
await context.MapAsync<Timesheet>();
context.SaveChanges();

You will get an error:
System.InvalidOperationException: 'An error was generated for warning 'Microsoft.EntityFrameworkCore.Query.InvalidIncludePathError': Unable to find navigation 'RowVersion' specified in string based include path 'RowVersion'. This exception can be suppressed or logged by passing event ID 'CoreEventId.InvalidIncludePathError' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.'

This started to happen with versions higher than 6.0.6

Here is sample code
[ConsoleApp2.zip](https://github.com/leonardoporro/Detached-Mapper/files/10407427/ConsoleApp2.zip)

**Comment by traiannemes** [comment]
Thank you and much appreciated, I am looking forward to a fix for this in the upcoming releases. Detached mapper has been a life saver for my projects, so much easier and less code.

**Comment by leonardoporro** [comment]
Awesome... 
I'm adding more features and building a wiki [here](https://github.com/leonardoporro/Detached-Mapper/wiki/Mapping-Graphs-(DTO-to-Entity)).
It's a lot of work! 
Reading docs, recommending the library, writting code for it or anything else is much appreciated!

**Comment by leonardoporro** [comment]
This should work for 7.0.0 (still compatible with .net 6)

**Comment by traiannemes** [comment]
It's not working for me with the same example attached to this issue. I am getting the same error message.

**Comment by leonardoporro** [comment]
Sorry, on it just right now.. there are 2 scenarios in which this could happen, I fixed only one

**Comment by leonardoporro** [comment]
Uploaded 7.0.1
For a free lib, you can't say that the support is slow :)

**Comment by traiannemes** [comment]
That I will never say :) Thank you, it's working like a charm now :)
