### ISSUE TITLE
Upon inserting entities return the newly seeded values for primary keys

### ISSUE THREAD

**Issue by traiannemes** [leonardoporro/Detached-Mapper#70]
**Describe the solution you'd like**
When calling EF like context.Add(entity) or context.Update(entity) for the all the records that EF inserts it returns back the seeded value for primary key. EF by default follows each INSERT with SELECT SCOPE_IDENTITY() when auto-generated Ids are used.

It would be nice to have similar functionality with context.MapAsync(entity) follow by context.SaveChanges()
**Describe alternatives you've considered**
Right now I call another end point (if it's an API) to get the newly inserted record

**Additional context**

**Comment by leonardoporro** [comment]
Hi @traiannemes,
Ok, first thing would be checking that you are using the return value of MapAsync and not the entity that you passed as a parameter (they are not the same!).
MapAsync takes a DTO that may or may not be of type TEntity, loads a TEntity from the DB using the key of the given parameter and copies the matching properties recursively.
At the end it returns the instance of TEntity that was loaded from the DB by EF using a regular query and that should include all EF configs and magics.
Secondly, I let EF to handle as much as possible, the modify state, so maybe a call to ChangeTracked.DetectChanges may be needed for some value to be calculated (?) I'm not sure about this...
I'd really appreciate if you attach a piece of code to have more context on this.

**Comment by traiannemes** [comment]
Thank you Leonardo for the clarification, I assume next time I should pay more attention to your wiki pages :) I will close this ticket and thank you again for the explanation.

**Comment by leonardoporro** [comment]
Glad it worked!
