### ISSUE TITLE
Ignore Data Annotation

### ISSUE THREAD

**Issue by Letsion** [leonardoporro/Detached-Mapper#84]
**Is your feature request related to a problem? Please describe.**
The following situation:
What if you don't want to save things in the DB, but still want to map them?
This does not work with the solution to use `[NotMapped]` as Ignore attribute.

**Describe the solution you'd like**
Use a custom attribute such as `[Ignore]`.

**Describe alternatives you've considered**
Removed `[NotMapped]` attribute and implemented the NotMapped feature in EF Core via Fluent API.

Example:
```csharp
modelbuilder.Entity<...>().Ignore(e => e.[Property)
```

**Comment by leonardoporro** [comment]
[MapIgnore] implemented in 7.1.1
[NotMapped] still working, but removes the mapping for EF also.
Let me know if it works.

**Comment by Letsion** [comment]
I would want just the opposite. I would want it to map but I would want it to map anyway with the annotation [NotMapped] but not automatically ignore the mapping.

**Comment by leonardoporro** [comment]
I think it makes sense to stop using that attribute. 
I need to create a breaking changes list in the wiki and do that.

Meanwhile, if you don't want it to be processed, you can remove the handler when calling UseMapper:

`
mappeOptions.AnnotationHandlers.Remove(typeof(NotMappedAttribute))
`

**Comment by leonardoporro** [comment]
done in 7.1.5

**Comment by Letsion** [comment]
Thank you. Now it allows us to disable EF core mapping but not Dto to entity mapping
