### ISSUE TITLE
MapperException: Can't find a concrete type for abstract type or interface

### ISSUE THREAD

**Issue by tschumpr** [leonardoporro/Detached-Mapper#98]
Hi
I'm trying to use Detached-Mapper as a replacement for GraphDiff. One of my entities has a property of abstract type [NetTopologySuite.Geometries.Geometry](https://nettopologysuite.github.io/NetTopologySuite/api/NetTopologySuite.Geometries.Geometry.html) which leads to the following error:

```
public class Dataset
{
  public Geometry BoundingBoxPreview { get; set; }
}
```

> Detached.Mappers.Exceptions.MapperException: Can't find a concrete type for abstract type or interface NetTopologySuite.Geometries.Geometry
 
with stack trace

> AbstractTypeMapperFactory.GetConcreteType(MapperOptions mapperOptions, Type abstractType)
AbstractTypeMapperFactory.Create(Mapper mapper, TypePair typePair)
ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
Mapper.GetTypeMapper(TypePair typePair)
LazyTypeMapper`2.get_Value()
lambda_method1795(Closure , Datensatz , Datensatz , IMapContext )
RootEntityTypeMapper`3.Map(TSource source, TTarget target, IMapContext context)
TypeMapper`2.Map(Object source, Object target, IMapContext context)
Mapper.Map(Object source, Type sourceClrType, Object target, Type targetClrType, IMapContext context)
EFMapper.Map[TEntity](DbContext dbContext, Object entityOrDTO, MapParameters parameters)
MappingDbContextExtensions.Map[TEntity](DbContext dbContext, Object entityOrDTO, MapParameters mapParams)

I've tried the following things:

- Using `[Abstract]` attribute: _Attribute 'Abstract' is not valid on this declaration type. It is only valid on 'class' declarations_ 
- Exclude Geometry: Code runs but `BoundingBoxPreview` is empty
```
.UseMapping(opt =>
{
    opt.Default(profOpt => profOpt.Type<Dataset>().Member(m => m.BoundingBoxPreview).Exclude<Dataset,Geometry>());
})
```

Is it possible to use abstract types from external libraries? If so, how can I configure it correctly?

**Comment by leonardoporro** [comment]
Hi!
That's one possible solution, if you have only 1 type of geometry.
If there are may, e.g.: Geometry -> Polygon, Geometry -> Ellipse, Geometry -> Rectangle you may configure Entity Framework's Inheritance using a discriminator. The mapper will pick the settings from there.

[https://github.com/leonardoporro/Detached-Mapper/blob/e6772f389d61fdc284c7ad1aed122cab2e299e80/test/Detached.Mappers.EntityFramework.Tests/Model/DefaultTestDbContext.cs#L54](https://github.com/leonardoporro/Detached-Mapper/blob/e6772f389d61fdc284c7ad1aed122cab2e299e80/test/Detached.Mappers.EntityFramework.Tests/Model/DefaultTestDbContext.cs#L54)
